import { jsPDF } from 'jspdf';

/**
 * PdfService - ANTIGRAVITY 合規證明產出引擎
 * 負責將 ESG 數據與數位證跡轉譯為 A4 PDF 報告
 */
export const PdfService = {
  /**
   * 生成一鍵合規包 PDF
   */
  generateComplianceReport: async (batchData) => {
    const doc = new jsPDF({
      orientation: 'p',
      unit: 'mm',
      format: 'a4'
    });

    const primaryColor = [0, 255, 0]; // Agric Neon Green
    const timestamp = new Date().toLocaleString();

    // 1. Header Section
    doc.setFillColor(0, 0, 0);
    doc.rect(0, 0, 210, 40, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.text("ANTIGRAVITY ESG COMPLIANCE", 20, 25);
    
    doc.setFontSize(10);
    doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.text(`CERTIFICATE ID: AG-${Date.now()}`, 20, 32);

    // 2. Impact Summary (GRI 305-5)
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    doc.text("1. IMPACT SUMMARY (GRI 305-5)", 20, 55);
    
    doc.setFontSize(12);
    doc.text(`Enterprise: ${batchData.enterprise || 'AgriGood Corp'}`, 25, 65);
    doc.text(`Batch Number: ${batchData.batch_number}`, 25, 72);
    doc.text(`Cumulative CO2e Reduction: ${batchData.impact.totalCarbonReduction} kg`, 25, 79);
    
    doc.setDrawColor(200, 200, 200);
    doc.line(20, 85, 190, 85);

    // 3. Evidence Section (Photo & GPS)
    doc.setFontSize(14);
    doc.text("2. DIGITAL EVIDENCE TRAIL", 20, 100);
    
    if (batchData.image) {
      try {
        // 加入原始照片 (Base64)
        doc.addImage(batchData.image, 'JPEG', 25, 110, 80, 60);
        
        doc.setFontSize(8);
        doc.setTextColor(100, 100, 100);
        doc.text(`GPS LOCATION: ${batchData.coords}`, 25, 175);
        doc.text(`CAPTURE TIMESTAMP: ${batchData.timestamp}`, 25, 180);
      } catch (err) {
        doc.text("[Image Data Unavailable]", 25, 120);
      }
    }

    // 4. Digital Signature & Integrity
    doc.setFillColor(240, 240, 240);
    doc.rect(20, 200, 170, 30, 'F');
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(10);
    doc.text("DIGITAL INTEGRITY HASH (HMAC-SHA256):", 25, 210);
    doc.setFontSize(8);
    doc.setFont("courier", "normal");
    doc.text(batchData.signature || "N/A", 25, 217);
    
    doc.setFont("helvetica", "bold");
    doc.setTextColor(0, 150, 0);
    doc.text("STATUS: VERIFIED BY ANTIGRAVITY SECURE PROTOCOL", 25, 225);

    // 5. Footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(`This document is dynamically generated by the ANTIGRAVITY STITCH Layer.`, 105, 280, { align: 'center' });
    doc.text(`© 2026 AGRIC AI SYSTEMS - GRI & TNFD COMPLIANT`, 105, 285, { align: 'center' });

    // Save PDF
    doc.save(`Compliance_Report_${batchData.batch_number}.pdf`);
  }
};
